
vagrant:
  hosts:
    remote:
      ansible_host: 10.11.10.11
      ansible_user: ubuntu

docker_container:
  hosts:
    neuro_docker:
      ansible_host: neuro_docker
      ansible_connection: docker

production:
  hosts:
    neuro:
