#!/usr/bin/env ansible-playbook
---

- hosts: all
  gather_facts: yes
  environment:
    - LC_ALL: '{{ locale }}'
    - LANG: '{{ locale }}'
  roles:
    - { role: bash, tags: [rc, bash, common] }
    - { role: common, become: yes, become_method: sudo, tags: common }
    - { role: java, become: yes, become_method: sudo, tags: common }
    - { role: python, tags: python }
    - { role: nipy, tags: nipy }
    - { role: neuro_pypes, tags: pypes }
    - { role: libraries, tags: libs }
