---

- name: common | Create directory {{ python_env_dir }}
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
  loop:
    - '{{ python_env_dir }}'
  become: yes
  become_method: sudo

- import_tasks: clone.yml
  tags: clone_pypes

- name: Copy Pipfile
  copy:
    src: Pipfile
    dest: "{{ python_env_dir }}/Pipfile"

- name: Create .envrc file
  blockinfile:
    path: "{{ python_env_dir }}/.envrc"
    mode: 0644
    owner: '{{ user }}'
    group: '{{ group }}'
    create: yes
    block: |
      export PIPENV_VENV_IN_PROJECT=./.venv/

- name: Enable the .envrc file
  command: >
    direnv allow .
  args:
    chdir: "{{ python_env_dir }}"

- name: Install requirements
  command: >
    pipenv install --dev
  args:
    chdir: "{{ python_env_dir }}"
