---

- include_tasks: dependencies.yml

- include_tasks: python_env.yml

- name: Copy requirements file
  copy:
    src: requirements.txt
    dest: "{{ tmp_install_dir }}/requirements.txt"

- name: Install requirements
  pip:
    requirements: "{{ tmp_install_dir }}/requirements.txt"
    virtualenv: "{{ python_env_dir.stdout }}"
