---

- name: neurodebian | Download the NeuroDebian repository sources list file
  get_url:
    url: http://neuro.debian.net/lists/{{ ansible_distribution_release }}.de-m.full
    dest: '{{ home_dir }}/neurodebian.sources.list'
    mode: 0440

- name: neurodebian | Add the NeuroDebian repository sources to APT
  block:
  - slurp:
      src: '{{ home_dir }}/neurodebian.sources.list'
    register: repos

  - apt_repository:
      repo: '{{ item }}'
      state: present
      filename: neurodebian
    vars:
      repo_sources: "{{ repos['content'] | b64decode }}"
    with_items:
      - "{{ repo_sources.split('\n') }}"
    when:
      - item != '' and not item.startswith('#')
    become: yes
    become_method: sudo

# - name: neurodebian | Add APT signing key
#   apt_key:
#     id: "0xA5D32F012649A5A9"
#     keyserver: "hkp://pool.sks-keyservers.net:80"
#     state: "present"
#   become: yes
#   become_method: sudo

- name: neurodebian | Copy APT PGP key file
  copy:
    src: NeuroDebian.Archive.Key.Public.asc
    dest: "{{ home_dir }}"

- name: neurodebian | Add APT signing key
  apt_key:
    id: "0xA5D32F012649A5A9"
    file: "{{ home_dir }}/NeuroDebian.Archive.Key.Public.asc"
    state: "present"
  become: yes
  become_method: sudo

- name: neurodebian | Remove APT PGP key file
  file:
    path: "{{ home_dir }}/NeuroDebian.Archive.Key.Public.asc"
    state: absent

- name: Update APT cache
  apt:
    update_cache: yes
  become: yes
  become_method: sudo

- name: Install APT packages
  apt:
    name:
    - dicomnifti
    - bison
    state: present
    allow_unauthenticated: yes
  with_items:
  become: yes
  become_method: sudo
